### PR TITLE
Fix #620

### LINKED ISSUE #602: Works fine with OpenAI, but local Ollama and LM-Studio fail with co-worker errors
When running local, i can't get past coworker errors.   When I run the exact same workflow on OpenAI (using the last Exa example, below), it works fine.

On local Ollama or LM-Studio, it seems to be sensitive to the search tool.  

With `search_tool = DuckDuckGoSearchRun()` I get errors like this:

```
Action 'Delegate work to Internet Research' don't exist, these are the only available Actions:
```

With ` search_tool = SerperDevTool()`
```
Action 'None (I will think of potential improvements without using any tools)' don't exist
```
With `search_tool = ExaSearchTool.search`

```
Action Input: "epigenetics site:.edu OR site:.gov" I encountered an error while trying to use the too
```
With `search_tool = ExaSearchTool.search` AND `find_similar_tool = ExaSearchTool.find_similar` AND 
`search_and_contents_tool = ExaSearchTool.search_and_contents`

```
Error executing tool. Co-worker mentioned not found, it must to be one of the following options:
- internet research

```
'internet research' definitely exists...

CrewAI does not seem to play nice with anything local, and I have tried dozens of different configs :/

Presumably, the tools are working the same, so perhaps the OpenAI API is not as compatible as claimed for Ollama and LMS? Or, it is something related to CrewAI?

The very simple  code I am using to test is at https://github.com/tholonia/crewai-blogger/blob/main/blogger_v0.py

The log outputs are 
https://github.com/tholonia/crewai-blogger/blob/main/output_ddgs.log
https://github.com/tholonia/crewai-blogger/blob/main/output_exa.log
https://github.com/tholonia/crewai-blogger/blob/main/output_openai.md
https://github.com/tholonia/crewai-blogger/blob/main/output_serper.log

### LINKED ISSUE #620: Error "Co-worker mentioned not found..." when using with local llama3
With the example below I get the following error:
```
Error executing tool. Co-worker mentioned not found, it must to be one of the following options:
- pilot
```

```python
from crewai import Agent, Task, Crew

from langchain_community.llms import Ollama

import os

os.environ["OPENAI_API_KEY"] = "NA"


llm = Ollama(model="llama3")


# Agents
luke = Agent(
    role="pilot",
    goal="Destroy the Death Star",
    backstory="The young destined-to-be-Jedi pilot, summoned to attack the Death Star.",
    llm=llm,
)

leia = Agent(
    role="strategist",
    goal="Coordinate the attack on the Death Star",
    backstory="The Rebel leader, essential for strategy and communication.",
    llm=llm,
)

# Tasks
coordinate_attack = Task(
    description="""Leia must coordinate the mission,
    maintaining communication and providing strategic support.
    Leia must ensure that everything is in order, providing a safe path for Luke""",
    expected_output="""Successfully coordinated attack, Death Star destroyed. All units informed and aligned.""",
    agent=leia,
    allow_delegation=True,
)


destroy_death_star = Task(
    description="""Luke must pilot his X-Wing and shoot at the Death Star's weak point to destroy it.""",
    expected_output="""Death Star destroyed, mission successful.""",
    agent=luke,
)


# Crews
rebel_alliance = Crew(
    agents=[leia, luke],
    tasks=[coordinate_attack, destroy_death_star],
    verbose=2,
)


rebel_alliance.kickoff()
```

### PR DESCRIPTION
**Pull request by italovieira**
By investigating I noticed using crewAI with ollama + ollama3 that in some cases the `agent` parameter below comes with leading or trailing quote like `agent = '"pilot'`. There is a code to reproduce the bug in the description of #620.
 https://github.com/joaomdmoura/crewAI/blob/1e112fa50a27e13dd471feca5543932f46aa5176/src/crewai/tools/agent_tools.py#L52

This causes the comparison below to be false raising the error "Co-worker mentioned not found...". https://github.com/joaomdmoura/crewAI/blob/1e112fa50a27e13dd471feca5543932f46aa5176/src/crewai/tools/agent_tools.py#L58

I think this is the reason there was a `.strip(")` at  https://github.com/joaomdmoura/crewAI/blob/bcb57ce5f9b359d933870f66634109ce269989c1/src/crewai/tools/tool_usage.py#L354
So I've added back to fix #620.

### CODE REVIEW

**Review by ronenfilho — COMMENTED** [review]
While the original code replaces all double quotes inside the string with escaped double quotes, the updated code first removes any leading or trailing double quotes from the value string before applying the replacement. This ensures that any double quotes at the ends are not escaped unnecessarily. This can prevent double escaping in cases where the string might already be wrapped in double quotes.

**Comment by rundeks** [comment]
I'm having the same issue and would love to see this merged.

**Comment by felixgao** [comment]
I am seeing something similar when using Ollama with various models 

llama3
```
Error executing tool. Co-worker mentioned not found, it must to be one of the following options:
- editor
- newsfetcher
- newsanalyzer
- newslettercompiler
```


mistral
```
Action 'Delegate work to newsfetcher' don't exist, these are the only available Actions:
 Delegate work to co-worker: Delegate work to co-worker(task: str, context: str, coworker: Optional[str] = None, **kwargs) - Delegate a specific task to one of the following co-workers: [editor, newsfetcher, newsanalyzer, newslettercompiler]
The input to this tool should be the co-worker, the task you want them to do, and ALL necessary context to execute the task, they know nothing about the task, so share absolute everything you know, don't reference things but instead explain them.
Ask question to co-worker: Ask question to co-worker(question: str, context: str, coworker: Optional[str] = None, **kwargs) - Ask a specific question to one of the following co-workers: [editor, newsfetcher, newsanalyzer, newslettercompiler]
The input to this tool should be the co-worker, the question you have for them, and ALL necessary context to ask the question properly, they know nothing about the question, so share absolute everything you know, don't reference things but instead explain them.
```

would love to see it fixed.

**Comment by SYip** [comment]
It fix the issue for `llama3`, however, `llama3:8b-instruct-q8_0` seems to have similar issue but it comes with leading `'`.

```
Action: Ask question to co-worker
Action Input: {"question": "Can you explore the market size and growth prospects for AI-powered clinical documentation tools? What are some key players in this space, and what are their competitive strengths and weaknesses?", context: "As I was reading about the potential benefits of generative-AI technology in healthcare, I came across an article mentioning that the global clinical documentation software market is expected to grow significantly over the next few years. I'd like you to dig deeper into this topic and provide more insights on the market size, growth prospects, key players, and their competitive landscape.", coworker: 'Writer 


Error executing tool. Co-worker mentioned not found, it must to be one of the following options:
- writer
```

**Comment by gvieira** [comment]
Great catch! Should we also do the same for `'`?

**Comment by italovieira** [comment]
> Great catch! Should we also do the same for `'`?

Oh, I didn't get the problem with `'` but I think it's worth it since the change is minimal.

**Comment by gvieira** [comment]
Loved it! We are ready to merge this. Do you mind taking a look at the failing tasks?

**Comment by pythonbyte** [comment]
@italovieira 
Can you check if this PR is still relevant on newer versions?

**Comment by bhancockio** [comment]
No longer applicable.

**Pull request closed without merging**
