### PR TITLE
Performed spell check across the rest of code base, and enahnced the yaml paraser code a little

### PR DESCRIPTION
**Pull request by rumble773**

### CODE REVIEW

**Comment by rumble773** [comment]
Been a while hope you are alright @joaomdmoura!!

**Comment by joaomdmoura** [comment]
Hey @rumble773, yeah sorry, things got a little busy with crew but all good problems!
I see there are some minor conflicts, would you mind squashing those? 🙏🏼

**Comment by rumble773** [comment]
@joaomdmoura I seee, yallaa hope for all the best inshaAllah. 
> I see there are some minor conflicts, would you mind squashing those? 🙏🏼
I think I have squashed them, not sure why it still show in: 
```
 src/crewai/agent.py
tests/crew_test.py 
```
image

**Comment by rumble773** [comment]
Should be done now! 
Btw I gave a workshop about crewAI last week, great effort you guys are doing!!

**Comment by joaomdmoura** [comment]
How was the workshop, did people like it?

**Comment by rumble773** [comment]
It was great thanks for asking, people admire the solution!!! 
For me I really enjoyed giving a talk about crewAI and he multi agents systems.

**Pull request merged**
