### PR TITLE
Updated documentation with details about 'crewai create' command

### PR DESCRIPTION
**Pull request by Blanco10022**
I added a section in the readme file to show how to use 'crewAI create' command

### CODE REVIEW

**Comment by Blanco10022** [comment]
i did the necessary modifications , please check it out and merge it

**Review by ruebenramirez — APPROVED** [review]
Nice add!

**Comment by Blanco10022** [comment]
thanks , 
can you merge the PR

**Comment by ruebenramirez** [comment]
> can you merge the PR

I don't have write access to the repo.  I just wanted to help ease the burden of review :)

**Comment by joaomdmoura** [comment]
I like it, but for now only project creation is supported, so I might adjust it

**Comment by slavakurilyak** [comment]
@joaomdmoura it would be great to see crewAI use the new [external prompt file](https://github.com/joaomdmoura/crewAI/commit/672b1509720839de29b26fad40b38fd897f08d35) when running `crewai create`

**Review by gvieira — APPROVED** [review]
Awesome! Thanks for contributing!

**Comment by pythonbyte** [comment]
Thanks for the PR, but now is outdated with the actual CLI command which is
"crewai create crew/pipeline <project>"

**Pull request closed without merging**
