### PR TITLE
Enable telemetry opt-out #254

### PR DESCRIPTION
**Pull request by gardner**
Users can opt out of telemetry by setting the environment variable `CREWAI_TELEMETRY_OPT_OUT`

Fixes:

* #254
* #241
* #372

This branch has been published to https://pypi.org/project/crewai-clean for testing.

### CODE REVIEW

**Comment by raghav135** [comment]
As an software architect within a bank which has tons of firewall, such requests for enabling firewall will never get approved , without opting out feature, we will get errors in logs, and we will have a sub standard experience. Unfortunately for us, it would be a no go with crewai if we don't have an opt out of telemetry.

**Review by ruebenramirez — APPROVED** [review]

**Comment by ZQ-Dev8** [comment]
+1 on disabling telemetry for running in airgapped environments, any updates on this?

**Comment by arnaudgelas** [comment]
@joaomdmoura Can you have a look at this one, please?
Note in an enterprise environment this is a blocking point

**Comment by chander-pal** [comment]
@CodiumAI-Agent /review

**Review by nanda-nainadurai — APPROVED** [review]
This is a much-needed feature and the community has been championing this.

**Comment by tsukhu** [comment]
We are really loving this framework but this feature is important. will this be making it to a release soon. Must have as most of the enterprises will have approve a tool without opt-out.

**Comment by elsewhat** [comment]
This is a required option in order to gain enterprise adoption. For the future of crewAI I hope this gets approved by project owners.

**Comment by gardner** [comment]
I'm still keen to see this merged.

**Pull request closed without merging**
