### PR TITLE
docs: add spider docs

### PR DESCRIPTION
**Pull request by WilliamEspegren**
Twitter: [@WilliamEspegren](https://x.com/WilliamEspegren)

### CODE REVIEW

**Review by pythonbyte — COMMENTED** [review]
Thanks for the PR @WilliamEspegren, good work.

Can you please also add the SpiderTool reference to the mkdocs in alphabetical order?

**Comment by WilliamEspegren** [comment]
@pythonbyte Will do right away :)

**Comment by WilliamEspegren** [comment]
@pythonbyte ready to merge

**Comment by pythonbyte** [comment]
Thanks @WilliamEspegren 🚀

**Review by pythonbyte — APPROVED** [review]
LGTM ✅

**Pull request merged**
