### PR TITLE
Trying to add a max_token for the agents class

### PR DESCRIPTION
**Pull request by rumble773**
@joaomdmoura Not sure if this is the best or the right way, but I could use some help or guidelines to complete it in the right way.

### CODE REVIEW

**Comment by lorenzejay** [comment]
Hi @rumble773 , added the attribute, but it seems like handling the max_token is done when you set the `llm`

for example:

```
ChatOpenAI(
            model=os.environ.get("OPENAI_MODEL_NAME", "gpt-4o"),
            max_tokens=1000,
        ),
```

So we may not need our agent classses to set this

**Review by lorenzejay — COMMENTED** [review]
You would need to attach this passed max_tokens to the `llm`. so potentially after the validator you can set `self.llm = max_token`

**Comment by rumble773** [comment]
@lorenzejay Thank you for reviewing this! 
I do agree with you on the second though of setting it in `set_agent_executor`, but not super sure where to start exactly. 
Can you assist me in that? and I will write the test and the doc for sure.

**Comment by rumble773** [comment]
++ I think I shall close this commit, and try on a fresh one

**Pull request closed without merging**
