### PR TITLE
Accept Langchain's RunnableConfig to Agent.execute_task

### PR DESCRIPTION
**Pull request by whimo**
Accept config as an argument and forward it to the invoke() method of the underlying Langchain AgentExecutor.
It is very helpful for customizing the run, e.g. adding callbacks (see [docs](https://api.python.langchain.com/en/latest/runnables/langchain_core.runnables.config.RunnableConfig.html) for more)

### CODE REVIEW

**Comment by joaomdmoura** [comment]
I like it, but we would need to update the agent attributes as well to allow the config to be send upon instantiating

**Comment by gvieira** [comment]
Hey @whimo! Any thoughts on @joaomdmoura's suggestion to also update agente attributes?

**Comment by whimo** [comment]
> Hey @whimo! Any thoughts on @joaomdmoura's suggestion to also update agente attributes?

Nothing against it. In fact, we can just update #632 with this and close the 2 PRs altogether.

**Comment by gvieira** [comment]
@whimo I like the idea of closing both PRs and creating another one joining them, as we would have a conflict here anyway. Happy to streamline the review process for this new PR. cc @thehapyone

**Comment by whimo** [comment]
Hi @gvieira @thehapyone , I've updated this PR with changes from #632. Looking forward to a review.

**Comment by thehapyone** [comment]
Looks good to me 👌

**Review by gvieira — APPROVED** [review]
Great work!

**Comment by whimo** [comment]
Hi @gvieira, thanks for the approval, can we merge this now?

**Comment by joaomdmoura** [comment]
I would love to understand more what is the underlying need here before we merge, just because we override a lot of the the AgentExecutor and will probably keep overriding more, my fear is that this probably not accepts all the configs today and will probably break in the future.

**Comment by thehapyone** [comment]
> I would love to understand more what is the underlying need here before we merge, just because we override a lot of the the AgentExecutor and will probably keep overriding more, my fear is that this probably not accepts all the configs today and will probably break in the future.

The AgentExceutor is based on Langchain runnable or atleast everything is migrating towards runnable has a native object. The runnable configs provides a lot of possibilities to customise the behaviour of any type of runnable. A very good use case of this is native callback and tracing possibilities without having to add new functionality to the existing agents codebase. So unless, langchain drops supports for runnable or crewAI moves away from langchain can’t see how this is an issue now or later. The agent still has it’s own config parameter which is a totally different thing.

**Comment by whimo** [comment]
Hi @joaomdmoura! Really looking forward to merging this. If you have any questions or concerns, please let us know :)

P.S. This change should never break, because AgentExecutor is a Runnable, and any Runnable accepts a RunnableConfig in its `invoke()` method.
We need this for observability (using Langchain's run_manager, which automatically reports chains' start and end events).

**Comment by thehapyone** [comment]
Hi @joaomdmoura @gvieira can you guys check this out? This is really a nice thing to have

**Comment by thehapyone** [comment]
@whimo I think this PR won't work again and should probably be closed. CrewAI has moved away from using langchain in the agentexecutor

**Comment by whimo** [comment]
I believe you're right. The issue can be closed, but I'd love if CrewAI introduced its own callback mechanism similar to what Langchain and LlamaIndex have, so that we can use observability tools, add logging etc.

**Pull request closed without merging**
